(function(root){'use strict';
const MONTHS=['มกราคม','กุมภาพันธ์','มีนาคม','เมษายน','พฤษภาคม','มิถุนายน','กรกฎาคม','สิงหาคม','กันยายน','ตุลาคม','พฤศจิกายน','ธันวาคม'];
const WEEK=['อาทิตย์','จันทร์','อังคาร','พุธ','พฤหัสบดี','ศุกร์','เสาร์'];
const THAKSA_ORDER=[1,2,3,4,7,5,8,6];
const THAKSA_NAMES=['บริวาร','อายุ','เดช','ศรี','มูละ','อุตสาหะ','มนตรี','กาลกิณี'];
const STRENGTH={1:6,2:15,3:8,4:17,7:10,5:19,8:12,6:21};
const BASE_NAMES=[['อัตตะ','หินะ','ธนัง','ปิตา','มาตา','โภคา','มัชฌิมา'],['ตนุ','กดุมภะ','สหัชชะ','พันธุ','ปุตตะ','อริ','ปัตนิ'],['มรณะ','ศุภะ','กัมมะ','ลาภะ','พยายะ','ทาสา','ทาสี']];
const HOUSE_META={
'อัตตะ':['self','ตัวตนและแกนบุคลิก'],'หินะ':['health','จุดอ่อนหรือสิ่งที่เสื่อมง่าย'],'ธนัง':['money','รายได้ เงินหมุน และทรัพย์ที่เข้ามา'],'ปิตา':['work','ผู้ใหญ่ฝ่ายชาย อำนาจและหน้าที่'],'มาตา':['home','บ้าน การดูแล และรากฐาน'],'โภคา':['money','โภคทรัพย์และความกินอยู่'],'มัชฌิมา':['self','สมดุลและภาพรวม'],
'ตนุ':['self','ตัวเรา ร่างกาย และภาพที่แสดงออก'],'กดุมภะ':['money','ทรัพย์สะสม ฐานะ และการจัดการเงิน'],'สหัชชะ':['relation','เพื่อน เครือข่าย การติดต่อ'],'พันธุ':['home','บ้าน ญาติ ถิ่นฐาน'],'ปุตตะ':['relation','บุตร ผลงานสร้างสรรค์'],'อริ':['health','อุปสรรค คู่แข่ง และสุขภาพตามคติ'],'ปัตนิ':['relation','คู่ครอง หุ้นส่วน และคู่สัญญา'],
'มรณะ':['health','การเปลี่ยนผ่านและเรื่องที่ต้องระวัง'],'ศุภะ':['luck','ความรู้ ครู การเดินทางไกล และความก้าวหน้า'],'กัมมะ':['work','อาชีพ งานหลัก และหน้าที่'],'ลาภะ':['money','ผลตอบแทน โอกาส และเครือข่าย'],'พยายะ':['health','รายจ่าย ความเหนื่อย และการสูญเสีย'],'ทาสา':['work','ลูกน้อง ผู้ช่วย และงานบริการ'],'ทาสี':['work','ผู้ช่วยและคนใต้การดูแล']};
const DAYS800=292207,TU=800,EPOCH=373,UCCA=2611,APOGEE=3232,CS_JD_OFFSET=1954167,CAL_DAYS={A:354,B:355,C:384,c:384};
function toJD(year,month,day){let yp,mp;if(month===1||month===2){yp=year-1;mp=month+12}else{yp=year;mp=month}let B;if(year<1582||(year===1582&&month<10)||(year===1582&&month===10&&day<15))B=0;else{const A=Math.trunc(yp/100);B=2-A+Math.trunc(A/4)}const C=yp<0?Math.trunc(365.25*yp-.75):Math.trunc(365.25*yp);const D=Math.trunc(30.6001*(mp+1));return Math.trunc(B+C+D+day+1720995)}
function lsYear(year){const h=Math.floor((year*DAYS800+EPOCH)/TU)+1,kam=TU-((year*DAYS800+EPOCH)%TU),aq=Math.floor((h*11+650)/692);let avo=(h*11+650)%692;if(avo===0)avo=692;let t=(aq+h)%30;if(avo===692)t-=1;const wd=h%7,h1=Math.floor(((year+1)*DAYS800+EPOCH)/TU)+1,q1=Math.floor((h1*11+650)/692),t1=(q1+h1)%30;let langsak=Math.max(1,t),nyd=langsak;if(nyd<6)nyd+=29;nyd=(wd-nyd+1+35)%7;const leapday=kam<=207;let ct='A';if(t>24||t<6)ct='C';if(t===25&&t1===5)ct='A';if((leapday&&avo<=126)||(!leapday&&avo<=137))ct=ct!=='C'?'B':'c';let next=ct==='A'?(nyd+4)%7:ct==='B'?(nyd+5)%7:(nyd+6)%7;return{year,horakhun:h,kammacapon:kam,tithi:t,weekday:wd,langsak,nyd,next_nyd:next,leapday,cal_type:ct,caldays:CAL_DAYS[ct],offset:false}}
function calcYear0(year){const y=[lsYear(year-2),lsYear(year-1),lsYear(year),lsYear(year+1),lsYear(year+2)];for(let i=0;i<5;i++)if(y[2].tithi===24&&y[3].tithi===6){y[i].cal_type='C';y[i].next_nyd=(y[i].next_nyd+2)%7}for(let i=1;i<=3;i++)if(y[i].cal_type==='c'){const j=y[i].nyd===y[i-1].next_nyd?1:-1;y[i+j].cal_type='B';y[i+j].next_nyd=(y[i+j].next_nyd+1)%7}for(let i=1;i<=3;i++)if(y[i-1].next_nyd!==y[i].nyd&&y[i].next_nyd!==y[i+1].nyd){y[i].offset=true;y[i].langsak++;y[i].nyd=(y[i].nyd+6)%7;y[i].next_nyd=(y[i].next_nyd+6)%7}for(let i=0;i<5;i++){if(y[i].cal_type==='c')y[i].cal_type='C';y[i].caldays=CAL_DAYS[y[i].cal_type]}y[2].offset_days=y[2].langsak;if(y[2].offset_days<(6+(y[2].offset?1:0)))y[2].offset_days+=29;return y[2]}
const FIND={A:[[383,16],[354,15],[324,12],[295,11],[265,10],[236,9],[206,8],[177,7],[147,6],[118,5],[88,4],[59,3],[29,2]],B:[[384,16],[355,15],[325,12],[296,11],[266,10],[237,9],[207,8],[178,7],[148,6],[119,5],[89,4],[59,3],[29,2]],C:[[384,15],[354,12],[325,11],[295,10],[266,9],[236,8],[207,7],[177,6],[148,5],[118,14],[88,13],[59,3],[29,2]]},LUNAR_MONTHS=[0,5,6,7,8,9,10,11,12,1,2,3,4,8,88,15,16];
function findLunar(cal,days){let m=LUNAR_MONTHS[1],d=days;for(const [a,b] of FIND[cal]){if(d>a){d-=a;m=LUNAR_MONTHS[b];break}}return{monthRaw:m,month:(m===15||m===16)?m-10:m,day:d}}
function fromYD(year,days){let y0=calcYear0(year),sy=365+(y0.leapday?1:0);while(days>sy){year++;days-=sy;y0=calcYear0(year);sy=365+(y0.leapday?1:0)}const md=findLunar(y0.cal_type,y0.offset_days+days);return{csYear:year,...md,calType:y0.cal_type,horakhun:y0.horakhun+days}}
function thaiLunar(y,m,d){const jd=toJD(y,m,d),hk=jd-CS_JD_OFFSET;let cy=Math.floor((hk*800-373)/292207),days;if(hk%292207===95333){cy--;days=365}else{const y0=calcYear0(cy);days=hk-y0.horakhun}const z=fromYD(cy,days),idx=((z.csYear+11)%12)||12,animals=[null,'ชวด','ฉลู','ขาล','เถาะ','มะโรง','มะเส็ง','มะเมีย','มะแม','วอก','ระกา','จอ','กุน'];return{...z,jd,naksatr:animals[idx],phase:z.day<=15?'ขึ้น':'แรม',phaseDay:z.day<=15?z.day:z.day-15}}
function lunarString(l){return `${l.phase} ${l.phaseDay} ค่ำ เดือน ${l.month}${l.monthRaw===88?' (เดือน 8 หลัง)':''} ปี${l.naksatr}`}
function seq7(start){return Array.from({length:7},(_,i)=>((start-1+i)%7)+1)}
function animalIndex(name){return ['ชวด','ฉลู','ขาล','เถาะ','มะโรง','มะเส็ง','มะเมีย','มะแม','วอก','ระกา','จอ','กุน'].indexOf(name)+1}
function normalizeProfile(raw){const be=Number(raw.year),y=be>2400?be-543:be,d=Number(raw.day),m=Number(raw.month);return{name:(raw.name||'').trim(),d,m,y,yRaw:be,h:raw.hour==null?'':String(raw.hour),mi:raw.minute==null?'':String(raw.minute),place:(raw.place||'').trim()}}
function validProfile(v){if(!v.name||!Number.isInteger(v.d)||!Number.isInteger(v.m)||!Number.isInteger(v.y))return false;const x=new Date(v.y,v.m-1,v.d);if(x.getFullYear()!==v.y||x.getMonth()!==v.m-1||x.getDate()!==v.d)return false;if(v.h!==''&&(Number(v.h)<0||Number(v.h)>23||Number(v.mi)<0||Number(v.mi)>59))return false;return true}
function astroDate(v){let dt=new Date(v.y,v.m-1,v.d);if(v.h!==''&&Number(v.h)<6)dt=new Date(v.y,v.m-1,v.d-1);return{y:dt.getFullYear(),m:dt.getMonth()+1,d:dt.getDate(),weekday:dt.getDay()}}
function birthPlanet(v){const ad=astroDate(v);let planet=[1,2,3,4,5,6,7][ad.weekday];if(ad.weekday===3&&v.h!==''&&(Number(v.h)>=18||Number(v.h)<6))planet=8;return{planet,ad}}
function thaksaFor(p){const start=THAKSA_ORDER.indexOf(p),arr=[];for(let i=0;i<8;i++)arr.push(THAKSA_ORDER[(start+i)%8]);return arr}
function roleOfPlanet(t,p){const i=t.indexOf(p);return i>=0?THAKSA_NAMES[i]:'ไม่พบ'}
function mahasatta(v,l){const bp=birthPlanet(v),b1=seq7(bp.planet===8?4:bp.planet),b2=seq7(((l.month-1)%7)+1),b3=seq7(((animalIndex(l.naksatr)-1)%7)+1),b4=b1.map((n,i)=>n+b2[i]+b3[i]);return{rows:[b1,b2,b3],sum:b4}}
function positionRecords(m){const out=[];for(let r=0;r<3;r++)for(let c=0;c<7;c++){const name=BASE_NAMES[r][c],num=m.rows[r][c],meta=HOUSE_META[name];out.push({base:r+1,col:c+1,name,num,topic:meta[0],scope:meta[1]})}return out}
function pick(records,name){return records.find(x=>x.name===name)}
function ageYears(v,target){const b=new Date(v.y,v.m-1,v.d,12),t=new Date(target.getFullYear(),target.getMonth(),target.getDate(),12);return Math.max(0,(t-b)/86400000/365.2425)}
function mahaTaksaAt(v,target){const bp=birthPlanet(v).planet,start=THAKSA_ORDER.indexOf(bp),age=ageYears(v,target),cy=((age%108)+108)%108;let acc=0,main=THAKSA_ORDER[start],mainStart=0;for(let step=0;step<8;step++){const p=THAKSA_ORDER[(start+step)%8],dur=STRENGTH[p];if(cy<acc+dur){main=p;mainStart=acc;break}acc+=dur}const within=cy-mainStart,mi=THAKSA_ORDER.indexOf(main);let sub=main,sacc=0;for(let step=0;step<8;step++){const p=THAKSA_ORDER[(mi+step)%8],dur=STRENGTH[main]*STRENGTH[p]/108;if(within<sacc+dur){sub=p;break}sacc+=dur}return{age,cycleAge:cy,main,sub}}
function buildFacts(profile,target=new Date()){const v=normalizeProfile(profile);if(!validProfile(v))throw new Error('PROFILE_INVALID');const ad=astroDate(v),l=thaiLunar(ad.y,ad.m,ad.d),bp=birthPlanet(v),t=thaksaFor(bp.planet),m=mahasatta(v,l),records=positionRecords(m),mt=mahaTaksaAt(v,target);return{profile:v,astroDate:ad,lunar:l,birthPlanet:bp.planet,thaksa:t,matrix:m,records,mahaTaksa:mt,target,helpers:{pick:(name)=>pick(records,name),role:(p)=>roleOfPlanet(t,p)}}}
function selfTest(){const a=thaiLunar(2000,1,1);if(!(a.csYear===1361&&a.month===1&&a.day===24&&a.naksatr==='เถาะ'))return false;const f=buildFacts({name:'T',day:1,month:3,year:2516,hour:12,minute:0},new Date(2026,8,30));return f.records.length===21&&f.thaksa.length===8&&new Set(f.thaksa).size===8&&f.matrix.rows.every(r=>r.length===7)}
const API={MONTHS,WEEK,THAKSA_ORDER,THAKSA_NAMES,STRENGTH,BASE_NAMES,HOUSE_META,thaiLunar,lunarString,normalizeProfile,validProfile,birthPlanet,thaksaFor,roleOfPlanet,mahasatta,positionRecords,pick,mahaTaksaAt,buildFacts,selfTest};
root.AstroCore=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})(typeof globalThis!=='undefined'?globalThis:this);