(function(root){'use strict';
function deps(){if(!root.AstroCore||!root.AstroKnowledge||!root.AstroRules||!root.AstroSources)throw new Error('INTERPRETATION_DEPENDENCY_MISSING')}
function resolveSources(ids){return (ids||[]).map(id=>({id,source:root.AstroSources.get(id)})).filter(x=>x.source)}
function houseReading(facts,house,field){const rec=facts.records.find(x=>x.name===house);if(!rec)return null;const p=root.AstroKnowledge.getPlanet(rec.num),h=root.AstroKnowledge.HOUSES[house];return{house,number:rec.num,planet:p.name,field,text:root.AstroKnowledge.getMeaning(rec.num,field),houseMeaning:h?h.meaning:rec.scope,sourceRefs:[...new Set([...(p.sourceRefs||[]),'SEVEN-NUMBER-MAHAMODO'])],verification:p.verification}}
function positionalReading(facts,key){const rule=root.AstroKnowledge.POSITION_RULES[key];if(!rule)return null;const rec=facts.records.find(x=>x.base===rule.selector.base&&x.col===rule.selector.col);if(!rec)return null;const p=root.AstroKnowledge.getPlanet(rec.num);return{key,label:rule.label,base:rec.base,col:rec.col,number:rec.num,planet:p.name,text:root.AstroKnowledge.getMeaning(rec.num,rule.knowledgeField),sourceRefs:[...new Set([...(p.sourceRefs||[]),...(rule.sourceRefs||[])])],verification:p.verification}}
function transitEvidence(facts,rule){const mt=facts.mahaTaksa,mainRole=facts.helpers.role(mt.main),subRole=facts.helpers.role(mt.sub),roles=root.AstroRules.TRANSIT_ROLE_MEANINGS;let state='balanced';if(mainRole==='กาลกิณี'||subRole==='กาลกิณี')state='caution';else if([mainRole,subRole].some(x=>rule.transitRoles.includes(x)&&roles[x]&&roles[x].tone==='support'))state='support';else if([mainRole,subRole].some(x=>x==='อุตสาหะ'))state='effort';return{state,main:{number:mt.main,name:root.AstroKnowledge.getPlanet(mt.main).name,role:mainRole,roleMeaning:roles[mainRole]},sub:{number:mt.sub,name:root.AstroKnowledge.getPlanet(mt.sub).name,role:subRole,roleMeaning:roles[subRole]},sourceRefs:['MAHATAKSA-MAHAMODO','TAKSA-TABLE-VIBHISHANA']}}
function confidence(evidence){let score=0,total=0;for(const e of evidence){total++;if(e.verification==='verified')score+=1;else if(e.verification==='provisional')score+=.55;else score+=.4}const ratio=total?score/total:0;return{ratio,label:ratio>=.85?'สูง':ratio>=.55?'กำลังตรวจทาน':'เบื้องต้น'}}
function build(service,facts,rule){deps();const houses={};for(const h of rule.houses){const r=houseReading(facts,h,rule.knowledgeField);if(r)houses[h]=r}const transit=transitEvidence(facts,rule),positional={speech:positionalReading(facts,'speech'),mind:positionalReading(facts,'mind'),residence:positionalReading(facts,'residence')};const ev=[...Object.values(houses),...Object.values(positional).filter(Boolean)];return{service,rule,houses,transit,positional,confidence:confidence(ev),sources:resolveSources([...new Set([...rule.sourceRefs,...transit.sourceRefs,...ev.flatMap(x=>x.sourceRefs||[])])])}}
const API={houseReading,positionalReading,transitEvidence,build,resolveSources,version:'1.2.0'};root.AstroInterpretation=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})(typeof globalThis!=='undefined'?globalThis:this);
