(function(root){'use strict';
function assertDeps(){if(!root.AstroCore||!root.AstroKnowledge||!root.AstroRules||!root.AstroInterpretation)throw new Error('ENGINE_DEPENDENCY_MISSING')}
function composeCareer(I){const k=I.houses['กัมมะ'],p=I.houses['ปิตา'];let lead=`แกนการงานอยู่ที่ดาว ${k.number} ${k.planet} ในเรือนกัมมะ จึงเด่นกับ ${k.text}`;if(p)lead+=` ส่วนบริบทผู้ใหญ่และอำนาจมีลักษณะของดาว ${p.number} ${p.planet}`;let action=I.transit.state==='support'?'ช่วงนี้มีแรงหนุนให้เดินหน้างานที่ใช้จุดแข็งเดิม โดยเฉพาะเมื่อประสานผู้ใหญ่หรือคนที่มีบทบาทถูกจังหวะ':I.transit.state==='caution'?'ช่วงนี้ควรตรวจเงื่อนไข งานค้าง และการสื่อสารกับผู้ใหญ่ให้ละเอียดก่อนเร่งตัดสินใจ':I.transit.state==='effort'?'ช่วงนี้ผลลัพธ์มาจากการลงแรงและจัดการรายละเอียดมากกว่าการรอจังหวะ':'ช่วงนี้เหมาะกับการประคองงานเดิม วางระบบ และสะสมผลงานก่อนขยาย';return{lead,action}}
function composeFinance(I){const d=I.houses['ธนัง'],g=I.houses['กดุมภะ'],l=I.houses['ลาภะ'];let lead=`ธนังได้ดาว ${d.number} ${d.planet} สะท้อนช่องทางรายได้ผ่าน ${d.text} ส่วนกดุมภะได้ดาว ${g.number} ${g.planet} บอกแนวทางสร้างฐานทรัพย์ผ่าน ${g.text}`;if(l)lead+=` ขณะที่ลาภะได้ดาว ${l.number} ${l.planet} จึงควรสังเกตโอกาสจาก ${l.text}`;let action=I.transit.state==='support'?'จังหวะปัจจุบันหนุนให้จัดระบบรายได้และต่อยอดช่องทางที่เข้ากับพื้นดวง มากกว่าตามโอกาสแบบไม่มีแผน':I.transit.state==='caution'?'ควรเน้นสภาพคล่อง ตรวจรายจ่ายและเงื่อนไขทางการเงินซ้ำก่อนรับความเสี่ยงใหม่':I.transit.state==='effort'?'การเงินช่วงนี้ต้องอาศัยการจัดระบบและลงแรงมากกว่าหวังผลเร็ว':'ให้รักษาสมดุลระหว่างรายรับ การเก็บ และการขยาย โดยใช้ข้อมูลจริงประกอบ';return{lead,action}}
function composeLove(I){const p=I.houses['ปัตนิ'],s=I.houses['สหัชชะ'];let lead=`ปัตนิได้ดาว ${p.number} ${p.planet} ลักษณะคู่ครองหรือหุ้นส่วนจึงมีแนวโน้ม ${p.text}`;if(s)lead+=` การคบหาและการสื่อสารรอบตัวมีลักษณะของดาว ${s.number} ${s.planet}`;let action=I.transit.state==='support'?'ช่วงนี้เหมาะกับการคุยให้ชัด สร้างความร่วมมือ และเปิดพื้นที่ให้ความสัมพันธ์พัฒนาอย่างเป็นธรรมชาติ':I.transit.state==='caution'?'ควรชะลอการสรุปแทนอีกฝ่าย ลดคำพูดที่กดดัน และตรวจความคาดหวังให้ตรงกัน':I.transit.state==='effort'?'ความสัมพันธ์ช่วงนี้ต้องใช้ความอดทนและการสื่อสารสม่ำเสมอมากกว่าการคาดหวังผลทันที':'ให้ใช้การสื่อสารสม่ำเสมอและดูการกระทำจริงมากกว่าการคาดเดา';return{lead,action}}
function publicResult(service,rule,facts,I,c){return{service,label:rule.label,facts:{profile:facts.profile,lunar:facts.lunar},transit:I.transit,summary:c.lead,recommendation:c.action,publicBasis:rule.primary.map(h=>I.houses[h]).filter(Boolean).map(r=>`${r.house}: ${r.number} ${r.planet}`),knowledgeStatus:I.confidence.label,engineVersion:'1.2.0'}}
function analyze(service,profile,target=new Date()){assertDeps();const rule=root.AstroRules.RULES[service];if(!rule)throw new Error('SERVICE_UNKNOWN');const facts=root.AstroCore.buildFacts(profile,target),I=root.AstroInterpretation.build(service,facts,rule),c=service==='career'?composeCareer(I):service==='finance'?composeFinance(I):composeLove(I);return publicResult(service,rule,facts,I,c)}
function audit(service,profile,target=new Date()){assertDeps();const rule=root.AstroRules.RULES[service];if(!rule)throw new Error('SERVICE_UNKNOWN');const facts=root.AstroCore.buildFacts(profile,target);return{facts,interpretation:root.AstroInterpretation.build(service,facts,rule),rule,engineVersion:'1.2.0'}}
function selfTest(){try{const p={name:'T',day:1,month:3,year:2516,hour:12,minute:0};return ['career','finance','love'].every(s=>{const r=analyze(s,p,new Date(2026,9,1));return r.summary&&r.publicBasis.length&&r.engineVersion==='1.2.0'})}catch(e){return false}}
const API={analyze,audit,selfTest,version:'1.2.0'};root.AstroServiceEngine=API;if(typeof module!=='undefined'&&module.exports)module.exports=API;
})(typeof globalThis!=='undefined'?globalThis:this);
